### ISSUE TITLE
A combination of InlineStyles doesn't work. Neos-UI Version: "5.2.3"

### ISSUE THREAD

**Issue by chunpin** [techdivision/ckstyles#13]
Neos-UI Version: "5.2.3"

if I apply "fontSize" and 'fontColor' on the same element, only one of them will be rendered on the frontend.  
what's strange, is that it worked perfectly in the backend, but not frontend.

![Backend](https://user-images.githubusercontent.com/12544406/91849767-da30d080-ec5c-11ea-98b3-1992c7b1dba9.jpg)
![Frontend](https://user-images.githubusercontent.com/12544406/91849773-db61fd80-ec5c-11ea-8821-05867555dcb5.jpg)

**Comment by regniets** [comment]
Hi @chunpin - thanks for your report. This behavior was the same as we had with block styling.
It does apply the styles when chosen, but won't keep then in "formattingUnderCursor". I traced it back to ckeditor api, but did not come up with a solution - as the NeosUI provides this prop and the handling is not quite transparent.
When you reload the page, they most likely will be gone in the backend as well?

**Comment by pengmaradi** [comment]
Hi **@regniets** - I encountered the same problem. When I reload the page, InlineStyles remains in the backend, but BlockStyles does not exist anymore. Thanks.

**Comment by regniets** [comment]
Hi @pengmaradi, thanks for the report; this is actually the "formattingUnderCursor" issue. I'll give it another shot, hope i'll solve the problem...

**Comment by regniets** [comment]
The actual issue i see is:
formattingUnderCursor has the correct values
But when `change:data` is fired, ckeditor transmits `editor.getData()` to the ui-services `change` endpoint:
https://github.com/neos/neos-ui/blob/master/packages/neos-ui-ckeditor5-bindings/src/ckEditorApi.js#L73

If we have more than one block-style selectbox available, only the value of the first one is being transferred if chosen. If not, the value of the second box is submitted.

*Example:*  
Settings.yaml:
```
TechDivision:
  CkStyles:
    BlockStyles:
      presets:
        'color':
          label: 'Color'
          options:
            'green':
              label: 'Green'
              cssClass: 'color-green'
        'size':
          label: 'Size'
          options:
            'xl':
              label: 'XL'
              cssClass: 'size-xl'
```

Actual Source Code that i see in the browser when selecting both classes:
```
<p class="color-green size-xl">Text</p>
```

HTML that is submitted to the endpoint:
```
<p class="color-green">Text</p>
```
Maybe @dimaip or @sebobo have an idea?
