### ISSUE TITLE
Bug: Backend view of marked text is corrupted when not using autoparagraph: true

### ISSUE THREAD

**Issue by mhsdesign** [techdivision/ckstyles#22]
# Bug

When using the 'Neos.Demo:Content.Headline' in the Neos.Demo site-package the backend view of the marked text is corrupted after a reload/revisit.

(I tried it with another Site Package: https://github.com/patriceckhart/NeosCMS-Boilerplate and here it works...)

--------------

## **Steps to reproduce:**

1. Install Neos.Demo
2. Install techdivision/ckstyles
3. Define InlineStyle (In the Neos.Demo Settings.yaml):
```yaml
TechDivision:
  CkStyles:
    InlineStyles:
      presets:
        'fontColor':
          label: 'Font color'
          options:
            'red':
              label: 'Red'
              cssClass: 'my-class-red'
```
4. Allow to use `fontColor` formating for 'Neos.Demo:Content.Headline' (In the Neos.Demo NodeTypes.Content.Headline.yaml)
```yaml
'Neos.Demo:Content.Headline':
  properties:
    'title':
      ui:
        inline:
          editorOptions:
            inlineStyling:
              fontColor: true
```
5. Add `.my-class-red {color: red;}` (to Neos.Demo Public/Styles/Main.css)
6. Go to the frontend and login
7. Add a Headline Nodetype anywhere and color some part with the fontColor = Red
8. (Save) reload the page
9. See Issue:
The Headline Nodetype will first be displayed properly but after a few milliseconds the backend view of the Nodetype changes and the following html is rendered:
```html
<h1>I am a&nbsp;</h1>
<span>
    <span class="my-class-red">headline&nbsp;</span>
</span>
<h1>node with h1</h1>
```
The backend view before the reload and the frontend view is not impacted.
It shows the correct html:
```
<h1>I am a
    <span class="my-class-red">headline </span>
node with h1</h1>
```

--------------

## **After Step 7 ... not reloaded yet - just marked:**
![image](https://user-images.githubusercontent.com/85400359/123681843-95f56900-d84a-11eb-990c-5679466d6da4.png)

--------------

## **After any reload or revisit of the backend:**
![image](https://user-images.githubusercontent.com/85400359/123681902-a73e7580-d84a-11eb-9215-a697e8b862d3.png)

-------------

## **The frontend is not impactend:**
![image](https://user-images.githubusercontent.com/85400359/123682173-f4bae280-d84a-11eb-98a2-44ccc437bd8d.png)

-------------

## **In contrary the 'Neos.Demo:Content.Text' behaves normal.**

----------
techdivision/ckstyles @ latest
Neos/Flow 7.1 | PHP 7.4.18 | MariaDB 10.3.27
Neos/Demo (clean install)
Edge/Firefox @ latest
