### ISSUE TITLE
inlineStyles which contains more as one css class, on NEOS 7.1.1

### ISSUE THREAD

**Issue by FlorianHartl** [techdivision/ckstyles#23]
Hello there,

there is an issue with inlineStyles which contains more as one css class, on NEOS 7.1.1

If a new inlineStyles is applied and published its working well,
but if i reload or open this site at the Backend again, then only the first class (in this case .btn) will be applied.
So it could happen that a editor change any text within and dont notice that the button has the wrong style.

YAML:
```
TechDivision:
  CkStyles:
    InlineStyles:
      presets:
            'btn-secondary':
              label: 'Button secondary'
              cssClass: 'btn btn-secondary'
            'btn-secondary-outline':
              label: 'Button secondary outline'
              cssClass: 'btn btn-secondary btn-outline'
```
